In [1]:
import pandas as pd
import sqlite3

In [2]:
# conectamos con la base de datos my_database.db
connection = sqlite3.connect("database_cervezas.db")

# obtenemos un cursor que utilizamos para las queries
crsr = connection.cursor()

In [3]:
# Con esta función leemos los datos y lo pasamos a un DataFrame de Pandas
def sql_query(query):

    # Ejecuta la query
    crsr.execute(query)

    # Almacena los datos de la query 
    ans = crsr.fetchall()

    # Obtenemos los nombres de las columnas de la tabla
    names = [description[0] for description in crsr.description]

    return pd.DataFrame(ans,columns=names)

In [4]:
res = crsr.execute("SELECT name FROM sqlite_master WHERE type='table'")
for name in res:
    print(name[0])

cervezas
bares
empleados

In [5]:
# crea las tablas

In [6]:
query = '''

'''

crsr.execute(query)

In [7]:
query = '''

'''

crsr.execute(query)

In [8]:
query = '''

'''

crsr.execute(query)

In [9]:
query = '''

'''
crsr.execute(query)

In [10]:
query = '''

'''
crsr.execute(query)

In [11]:
query = '''

'''
# CRUD Create Register(insert) Update Delete
crsr.execute(query)

In [12]:
query = '''

'''
crsr.execute(query)

In [13]:
query = '''

'''
crsr.execute(query)

In [14]:
query = '''

'''
crsr.execute(query)

In [15]:
query = '''

'''
sql_query(query)

TypeError: 'NoneType' object is not iterable

In [ ]:
# 1 Obtener el nombre de los empleados que hayan repartido al bar Stop durante la semana 
# del 17 al 23 de octubre de 2005.

query = '''

'''

sql_query(query)

         Nombre
0  Carlos Lopez

In [ ]:
# 2 Obtener el Cif y nombre de los bares a los que se ha repartido cerveza de tipo Botella y
# capacidad inferior a 1 litro, ordenados por localidad

query = '''

'''

sql_query(query)

         Cif      Nombre
0  33333333Z  Otra Ronda
1  11111111X        Stop

In [ ]:
# 3. Obtener los repartos (nombre del bar, envase y capacidad de la bebida, fecha y cantidad)

query = '''

'''

sql_query(query)

       Nombre   Envase  Capacidad       Fecha  Cantidad
0        Stop  Botella       0.20  2005-10-21       240
1        Stop  Botella       0.33  2005-10-21        48
2   Las Vegas     Lata       0.33  2005-10-22        60
3  Otra Ronda   Barril      60.00  2005-10-22         4

In [ ]:
# 4. Obtener los bares a los que se les ha repartido envases de tipo botella y capacidad 0.2 o
# 0.33

query = '''

'''
sql_query(query)

       Nombre   Envase  Capacidad
0        Stop  Botella       0.20
1        Stop  Botella       0.33
2  Otra Ronda  Botella       0.20
3  Otra Ronda  Botella       0.33

In [ ]:
# 5. Nombre de los empleados que han repartido a los bares "Stop" y "Las Vegas" cervezas con
# envase botella.

query = '''

'''
sql_query(query)

  Nombre bar Nombre empleado   Envase
0       Stop    Carlos Lopez  Botella

In [ ]:
# 6. Obtener el nombre y número de viajes que ha realizado cada empleado fuera de Villa
# Botijo.

query = '''

'''
sql_query(query)

  CodE        Nombre  Viajes
0    1  Carlos Lopez       1
1    2    Rosa Perez       2
2    3  Luisa Garcia       2

In [ ]:
query = '''

'''
sql_query(query)

       Nombre   Localidad  litros
0  Otra Ronda  La Esponja  359.76

In [ ]:
# 7. Obtener el nombre y localidad del bar que más litros de cerveza ha comprado.

query = '''

'''
sql_query(query)

       Nombre   Localidad  litros
0  Otra Ronda  La Esponja  359.76

In [ ]:
# 8. Obtener los bares que han adquirido todos los tipos de cerveza con envase de botella y
# capacidad menor que 1 litro.

query = '''

'''
sql_query(query)

       Nombre
0        Stop
1  Otra Ronda

In [ ]:
#9. Subir un 5% el sueldo del empleado que más días haya trabajado.

query = '''

'''
sql_query(query)

   Dias_trabajados CodE        Nombre
0                3    2    Rosa Perez
1                2    3  Luisa Garcia
2                2    1  Carlos Lopez

In [ ]:
query = '''

'''
sql_query(query)

   t.Sueldo * 1.05
0         115500.0

In [ ]:
query = '''
   
'''
sql_query(query)

  CodE
0    2

In [ ]:
query = '''

'''
crsr.execute(query)

In [ ]:
query = '''

'''
sql_query(query)

  CodE      Nombre  Sueldo
0    2  Rosa Perez  115500